### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Mustwey** [Arroz-con/ShittyHub#1]
have you guys figured out how to read the other players selected pets in tradeapp? when i was trying to make an autotrader, thats the one thing i struggled on

**Comment by Mustwey** [comment]
if you guys have the solution to that, i would love to make an autotrader with you guys!

**Comment by Arroz-con** [comment]
i don't remember the path. but  its somewhere in like Player.PlayerGui.TradeGui. i cant check right now because executes are down right now

**Comment by Arroz-con** [comment]
i was thinking of making one too but I got too lazy. i was thinking one with values so it can trade automated like the bots on starpets

**Comment by Mustwey** [comment]
> i don't remember the path. but its somewhere in like Player.PlayerGui.TradeGui. i cant check right now because executes are down right now

what executor do u use? i have krampus and it seems to be working fine

**Comment by Mustwey** [comment]
my username on dc is aspecter0

**Comment by Mustwey** [comment]
> i don't remember the path. but its somewhere in like Player.PlayerGui.TradeGui. i cant check right now because executes are down right now

i just decided to get the trade data instead, its much cleaner
